use crate::*;

extern "C" {
    static mut namedfm: [xfmark_T; 36];
    pub fn setmark(mut c: i32) -> i32;
    pub fn free_fmark(mut fm: fmark_T);
    pub fn free_xfmark(mut fm: xfmark_T);
    pub fn clear_fmark(mut fm: *mut fmark_T);
    pub fn setmark_pos(mut c: i32, mut pos: *mut pos_T, mut fnum: i32) -> i32;
    pub fn setpcmark();
    pub fn checkpcmark();
    pub fn movemark(mut count: i32) -> *mut pos_T;
    pub fn movechangelist(mut count: i32) -> *mut pos_T;
    pub fn getmark_buf(mut buf: *mut buf_T, mut c: i32, mut changefile: bool) -> *mut pos_T;
    pub fn getmark(mut c: i32, mut changefile: bool) -> *mut pos_T;
    pub fn getmark_buf_fnum(mut buf: *mut buf_T, mut c: i32, mut changefile: bool, mut fnum: *mut i32) -> *mut pos_T;
    pub fn getnextmark(mut startpos: *mut pos_T, mut dir: i32, mut begin_line: i32) -> *mut pos_T;
    pub fn fmarks_check_names(mut buf: *mut buf_T);
    pub fn check_mark(mut pos: *mut pos_T) -> i32;
    pub fn clrallmarks(buf: *mut buf_T);
    pub fn fm_getname(mut fmark: *mut fmark_T, mut lead_len: i32) -> *mut u8;
    pub fn ex_marks(mut eap: *mut exarg_T);
    pub fn ex_delmarks(mut eap: *mut exarg_T);
    pub fn ex_jumps(mut eap: *mut exarg_T);
    pub fn ex_clearjumps(mut eap: *mut exarg_T);
    pub fn ex_changes(mut eap: *mut exarg_T);
    pub fn mark_adjust(mut line1: linenr_T, mut line2: linenr_T, mut amount: i64, mut amount_after: i64, mut op: ExtmarkOp);
    pub fn mark_adjust_nofold(mut line1: linenr_T, mut line2: linenr_T, mut amount: i64, mut amount_after: i64, mut op: ExtmarkOp);
    pub fn mark_col_adjust(mut lnum: linenr_T, mut mincol: colnr_T, mut lnum_amount: i64, mut col_amount: i64, mut spaces_removed: i32);
    pub fn cleanup_jumplist(mut wp: *mut win_T, mut checktail: bool);
    pub fn copy_jumplist(mut from: *mut win_T, mut to: *mut win_T);
    pub fn mark_jumplist_iter(iter: *const libc::c_void, win: *const win_T, fm: *mut xfmark_T) -> *const libc::c_void;
    pub fn mark_global_iter(iter: *const libc::c_void, name: *mut i8, fm: *mut xfmark_T) -> *const libc::c_void;
    pub fn mark_buffer_iter(iter: *const libc::c_void, buf: *const buf_T, name: *mut i8, fm: *mut fmark_T) -> *const libc::c_void;
    pub fn mark_set_global(name: i8, fm: xfmark_T, update: bool) -> bool;
    pub fn mark_set_local(name: i8, buf: *mut buf_T, fm: fmark_T, update: bool) -> bool;
    pub fn free_jumplist(mut wp: *mut win_T);
    pub fn set_last_cursor(mut win: *mut win_T);
    pub fn mark_mb_adjustpos(mut buf: *mut buf_T, mut lp: *mut pos_T);
}
